import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

interface ExportOptions {
  companyName: string;
  sectorName: string;
  baseYear: number;
}

/**
 * Captures the dashboard tab content as a multi-page PDF report.
 * Uses html2canvas to capture DOM elements, then assembles with jsPDF.
 */
export async function exportDashboardPDF(opts: ExportOptions): Promise<void> {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentW = pageW - margin * 2;

  // ── Cover Page ──
  pdf.setFillColor(79, 70, 229); // indigo-600
  pdf.rect(0, 0, pageW, pageH, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(12);
  pdf.text('TP TOOL', margin, 30);

  pdf.setFontSize(28);
  pdf.text('Climate Transition', margin, 80);
  pdf.text('Planning Report', margin, 95);

  pdf.setFontSize(14);
  pdf.setTextColor(200, 200, 255);
  pdf.text(opts.companyName, margin, 130);
  pdf.text(`${opts.sectorName} Sector`, margin, 142);

  pdf.setFontSize(11);
  pdf.text(`Base Year: ${opts.baseYear}`, margin, 165);
  pdf.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin, 177);

  pdf.setFontSize(9);
  pdf.setTextColor(180, 180, 230);
  pdf.text('This report was generated by the Climate Transition Planning Tool.', margin, pageH - 30);
  pdf.text('Data and projections are model-based estimates for planning purposes.', margin, pageH - 22);

  // ── Capture dashboard sections ──
  // Find all tab panels and capture the active one
  const tabPanels = document.querySelectorAll('[role="tabpanel"]');
  const visiblePanels = Array.from(tabPanels).filter(
    (el) => (el as HTMLElement).offsetParent !== null
  );

  // Also capture any visible card sections
  const dashboardContainer = document.querySelector('[data-dashboard-export]') ?? visiblePanels[0]?.parentElement;

  if (dashboardContainer) {
    // Capture the entire dashboard content
    const sections = dashboardContainer.querySelectorAll('.space-y-6 > *');
    const elements = sections.length > 0 ? Array.from(sections) : [dashboardContainer];

    for (const el of elements) {
      const htmlEl = el as HTMLElement;
      if (htmlEl.offsetParent === null) continue; // skip hidden

      try {
        const canvas = await html2canvas(htmlEl, {
          scale: 2,
          useCORS: true,
          backgroundColor: '#ffffff',
          logging: false,
        });

        const imgData = canvas.toDataURL('image/jpeg', 0.85);
        const imgW = contentW;
        const imgH = (canvas.height / canvas.width) * contentW;

        pdf.addPage();

        // Header
        pdf.setFillColor(249, 250, 251);
        pdf.rect(0, 0, pageW, 12, 'F');
        pdf.setTextColor(107, 114, 128);
        pdf.setFontSize(8);
        pdf.text(`${opts.companyName} | Climate Transition Report`, margin, 8);
        pdf.text(`Page ${pdf.getNumberOfPages()}`, pageW - margin - 15, 8);

        // Content image
        let yPos = 18;
        if (imgH > pageH - 30) {
          // Scale down if too tall
          const scale = (pageH - 30) / imgH;
          pdf.addImage(imgData, 'JPEG', margin, yPos, imgW * scale, imgH * scale);
        } else {
          pdf.addImage(imgData, 'JPEG', margin, yPos, imgW, imgH);
        }
      } catch {
        // Skip elements that fail to capture
      }
    }
  }

  // If no sections were captured, do a single full-page capture
  if (pdf.getNumberOfPages() <= 1) {
    const activePanel = visiblePanels[0] as HTMLElement | undefined;
    if (activePanel) {
      try {
        const canvas = await html2canvas(activePanel, {
          scale: 2,
          useCORS: true,
          backgroundColor: '#ffffff',
          logging: false,
        });

        const imgData = canvas.toDataURL('image/jpeg', 0.85);
        const imgW = contentW;
        const imgH = (canvas.height / canvas.width) * contentW;

        // Split into pages if needed
        let yOffset = 0;
        const maxPageContentH = pageH - 30;

        while (yOffset < imgH) {
          pdf.addPage();
          pdf.setFillColor(249, 250, 251);
          pdf.rect(0, 0, pageW, 12, 'F');
          pdf.setTextColor(107, 114, 128);
          pdf.setFontSize(8);
          pdf.text(`${opts.companyName} | Climate Transition Report`, margin, 8);
          pdf.text(`Page ${pdf.getNumberOfPages()}`, pageW - margin - 15, 8);

          // Calculate source crop
          const srcY = (yOffset / imgH) * canvas.height;
          const srcH = Math.min((maxPageContentH / imgH) * canvas.height, canvas.height - srcY);

          // Create cropped canvas
          const croppedCanvas = document.createElement('canvas');
          croppedCanvas.width = canvas.width;
          croppedCanvas.height = srcH;
          const ctx = croppedCanvas.getContext('2d');
          if (ctx) {
            ctx.drawImage(canvas, 0, srcY, canvas.width, srcH, 0, 0, canvas.width, srcH);
            const croppedImg = croppedCanvas.toDataURL('image/jpeg', 0.85);
            const croppedH = (srcH / canvas.width) * contentW;
            pdf.addImage(croppedImg, 'JPEG', margin, 18, imgW, croppedH);
          }

          yOffset += maxPageContentH;
        }
      } catch {
        // Fallback: just save the cover page
      }
    }
  }

  // Save
  const filename = `${opts.companyName.replace(/[^a-zA-Z0-9]/g, '_')}_Transition_Report_${new Date().toISOString().slice(0, 10)}.pdf`;
  pdf.save(filename);
}
